package com.sample.rules
 
import com.sample.DroolsTest.Alarme;
import com.sample.DroolsTest.SensorMov;
import com.sample.DroolsTest.CamVigilancia;
import com.sample.DroolsTest.Proprietario;
import com.sample.DroolsTest.Divisao;
import com.sample.DroolsTest.detecaoPerimetro;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
