package com.sample.rules
 
import com.sample.DroolsTest.Alarme;
import com.sample.DroolsTest.SensorMov;
import com.sample.DroolsTest.CamVigilancia;
import com.sample.DroolsTest.Proprietario;
import com.sample.DroolsTest.Divisao;
import com.sample.DroolsTest.detecaoPerimetro;
import com.sample.DroolsTest.TeamSecurity;

//$d: Divisao() esta sintaxe vai buscar um a um cada objeto

rule "Se for detetado uma pessoa na rua no horário de deteção, ativa o sistema de deteção interno da casa e notifica proprietário"
    when
    	$d: Divisao() 
        $i: Intruso(divisao=="rua")
        $cam: CamVigilancia(divisao=="rua",intruso == $i.isPessoa(), ligado == true, detecao == true)
        $cameras: CamVigilancia()
        $s: SensorMov()
    then
    	$s.setLigado(true);
    	update($s);
    	System.out.println( "Camaras da divisao " +$cameras.getDivisao() );
        $cameras.setLigado(true);
        update($cameras);
        System.out.println( "Camaras e Sensores das divisoes todas ativados" );
        
end


rule "Deixa de ser detetado uma pessoa na rua no horário de deteção e ninguém dentro de casa, desativa o sistema de deteção interno da casa"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


rule "Se for detetado uma pessoa na rua no horário de deteção, mas é introduzido um código válido à entrada de casa, o sistema de deteção interno da casa fica desativado"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


rule "Se for detetado uma pessoa na rua no horário de deteção, mas é introduzido um código inválido à entrada de casa, ativa fecho de portas nas entradas da casa"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


rule "Se for detetado um intruso dentro de uma divisão, ativado fecho da saída dessa divisão"
    when
        $d: Divisao()
        $i: Intruso(divisao==$d, true)
    then
        $d.setFecho(true);
        update($d);
        System.out.println("Intruso detetado, a fechar saida da divisao " + $i.getDivisao());
end


rule "Se ativado fecho da saída dessa divisão, ativa alarme"
    when
        $d: Divisao()
        $d.isFecho()==true
         
    then
        insert (new Alarme());
        System.out.println("Alarme ativado");
end


rule "Se alarme ativado avisar equipa segurança e proprietário"
    when
        $a: Alarme();
        $s: TeamSecurity();
        $p: Proprietario();
    then
        System.out.println("Avisando o proprietario" + $p.getNome() + " de numero: " + $p.getNumero + "e a equipa de segurança " + $.s.getNomeTeam + "de numero: " + $s.getNumero);
end


rule "Se equipa de segurança chegar à propriedade, desativa fecho das portas dessa divisão"
    when
    	$d: Divisao()
        $s: TeamSecurity(local == true)
    then
        $d.setFecho(false);
        update($d)
        System.out.println("Equipa de segurança chegou, a preparar para retirar o fecho das portas");
end


rule "Se equipa de segurança deteve intruso, desativar alarme e sistema de deteção interno da casa"
    when
        $s: TeamSecurity(deteve == true)
        $a: Alarme()
        $cam: CamVigilancia(!divisao.equals("rua"))
        $sens: SensorMov(!divisao.equals("rua"))
    then
        retract($a);
        $cam.setLigado(false);
        update($cam);
        $sens.setLigado(false);
        update($sens);
        System.out.println("Intruso detido, a desativar sistema interno da casa");
end


rule "Tudo OK"
    when
        not Alarm()
    then
        System.out.println("Tudo OK");
end


